### ISSUE TITLE
serverless environment variables in jest

### ISSUE THREAD

**Issue by rentrop** [americansystems/serverless-es6-jest#3]
Hi,

is there any way to get the serverless environment variables inside the jest-test?

In my `serverless.yml` i define them as follows:
```
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    myvar: 1
```

On lambda runtime this results in `process.env.myvar` being 1. But during jest tests these environment-variables are `undefined`

As a work around i use jest-globals inside the package.json. Unfortunately this makes me define the env-variables two times...
